### ISSUE TITLE
error TS2688: Cannot find type definition file for 'node' (typescript 2.1.5)

### ISSUE THREAD

**Issue by dyu** [ivijs/boilerplate#1]
```sh
yarn install
./node_modules/.bin/gulp
```

```
[19:26:15] Starting 'serve'...
[19:26:15] Starting 'copyAssets'...
[19:26:15] Finished 'copyAssets' after 30 ms
[19:26:15] Starting 'compileTypescript'...
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(6,22): error TS2420: Class 'SyntheticEvent<D>' incorrectly implements interface 'Event'.
  Property 'scoped' is missing in type 'SyntheticEvent<D>'.
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(52,22): error TS2420: Class 'SyntheticUIEvent<T>' incorrectly implements interface 'UIEvent'.
  Property 'scoped' is missing in type 'SyntheticUIEvent<T>'.
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(60,22): error TS2420: Class 'SyntheticKeyboardEvent' incorrectly implements interface 'KeyboardEvent'.
  Property 'scoped' is missing in type 'SyntheticKeyboardEvent'.
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(86,22): error TS2420: Class 'SyntheticMouseEvent<T>' incorrectly implements interface 'MouseEvent'.
  Property 'scoped' is missing in type 'SyntheticMouseEvent<T>'.
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(117,22): error TS2420: Class 'SyntheticTouchEvent' incorrectly implements interface 'TouchEvent'.
  Property 'scoped' is missing in type 'SyntheticTouchEvent'.
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(126,22): error TS2420: Class 'SyntheticPointerEvent' incorrectly implements interface 'PointerEvent'.
  Property 'scoped' is missing in type 'SyntheticPointerEvent'.
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(146,22): error TS2420: Class 'SyntheticDragEvent' incorrectly implements interface 'DragEvent'.
  Property 'scoped' is missing in type 'SyntheticDragEvent'.
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(154,22): error TS2420: Class 'SyntheticWheelEvent' incorrectly implements interface 'WheelEvent'.
  Property 'scoped' is missing in type 'SyntheticWheelEvent'.
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(171,22): error TS2420: Class 'SyntheticFocusEvent' incorrectly implements interface 'FocusEvent'.
  Property 'scoped' is missing in type 'SyntheticFocusEvent'.
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(178,22): error TS2420: Class 'SyntheticAriaRequestEvent' incorrectly implements interface 'AriaRequestEvent'.
  Property 'scoped' is missing in type 'SyntheticAriaRequestEvent'.
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(182,22): error TS2420: Class 'SyntheticClipboardEvent' incorrectly implements interface 'ClipboardEvent'.
  Property 'scoped' is missing in type 'SyntheticClipboardEvent'.
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(185,22): error TS2420: Class 'SyntheticErrorEvent' incorrectly implements interface 'ErrorEvent'.
  Property 'scoped' is missing in type 'SyntheticErrorEvent'.
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(196,22): error TS2420: Class 'SyntheticMediaEncryptedEvent' incorrectly implements interface 'MediaEncryptedEvent'.
  Property 'scoped' is missing in type 'SyntheticMediaEncryptedEvent'.
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(200,22): error TS2420: Class 'SyntheticMediaStreamErrorEvent' incorrectly implements interface 'MediaStreamErrorEvent'.
  Property 'scoped' is missing in type 'SyntheticMediaStreamErrorEvent'.
node_modules/ivi/dist/typings/events/synthetic_event.d.ts(203,22): error TS2420: Class 'SyntheticProgressEvent' incorrectly implements interface 'ProgressEvent'.
  Property 'scoped' is missing in type 'SyntheticProgressEvent'.
node_modules/ivi/dist/typings/vdom/stack_trace.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.

[19:26:17] 'compileTypescript' errored after 1.88 s
[19:26:17] Error: Command failed: ./node_modules/typescript/bin/tsc --importHelpers

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[19:26:17] 'serve' errored after 1.93 s

```

**Comment by localvoid** [comment]
Thanks, there were some breaking changes in typescript definition files during typescript 2.1 minor releases, some properties were added to `Event` interface, and I just didn't published ivi with a fix for this breaking change to npm. I didn't knew that anyone is using `ivi` right now. so I've temporarily stopped properly maintaining all this repos, and just focused on building a real project that will use this library.

The ivi code from the git repo should work with typescript 2.1.5 and >2.2.0. But I wouldn't recommend to use ivi, unless you have time on experiments, especially when dealing with bundlers/js compilers, because ivi code base is hugely depends on advanced optimizations that is done by google closure compiler, for example synthetic events API is designed specifically so that closure compiler could remove all unused code from production builds.

When I've started to work on ivi, I hoped that many of the problems with bundlers will be resolved in the near future and it will be quite easy to use something like closure compiler without ugly workarounds, but it is still an unpleasant experience when you try to use advanced toolchains for building javascript.

But there are still some hope :) node modules resolution algorithm is already commited in closure compiler repo and scope hoisting is on the roadmap for the next webpack version.
